const projects = [
  {
    id: 1,
    project_name: 'Weilerswist-Vernich',
    tasks: 'earthworks',
    skills_learned: '',
    start_date: '01.10.2011',
    end_date: '09.11.2011',
    longitude: 6.83333,
    latitude: 50.76667,
    description: 'Rescue excavation of an Iron Age trading post',
    city: 'Weilerswist',
    country: 'Germany',
    project_role: 'intern',
    project_type: 'Rescue excavation',
    organisation: 'LVR Rheinland',
  },
  {
    id: 2,
    project_name: 'Zülpich-Nemmenich',
    tasks: 'technical drawings, descriptions, earthworks',
    skills_learned:
      'technical drawings, descriptions based on the Rheiniches Stellenkartensystem',
    start_date: '10.11.2011',
    end_date: '10.01.2012',
    longitude: 6.681311,
    latitude: 50.688141,
    description: 'Rescue excavation of a Roman and Neolithic settlement.',
    city: 'Zülpich',
    country: 'Germany',
    project_role: 'intern',
    project_type: 'Rescue excavation',
    organisation: 'LVR Rheinland',
  },
  {
    id: 3,
    project_name: 'Brühl',
    tasks: 'technical drawings, descriptions',
    skills_learned: 'Working in really cold weather',
    start_date: '11.01.2012',
    end_date: '27.01.2012',
    longitude: 6.8987865,
    latitude: 50.8267554,
    description: 'Rescue excavation of a baroque garden',
    city: 'Brühl',
    country: 'Germany',
    project_role: 'intern',
    project_type: 'Rescue excavation',
    organisation: 'LVR Rheinland',
  },
  {
    id: 4,
    project_name: 'Mühlsteine',
    tasks: 'surveying with a total station',
    skills_learned: '',
    start_date: '28.01.2012',
    end_date: '31.01.2012',
    longitude: 6.484317,
    latitude: 50.692256,
    description: '',
    city: 'Nideggen',
    country: 'Germany',
    project_role: 'survey Assistent',
    project_type: 'Documentation project',
    organisation: 'LVR Rheinland',
  },
  {
    id: 5,
    project_name: 'Bunker',
    tasks: 'earthwork, surveying',
    skills_learned: 'documentation of a bunker',
    start_date: '01.02.2012',
    end_date: '29.02.2012',
    longitude: 6.650779,
    latitude: 50.611421,
    description:
      'Rescue excavation and revealing of a bunker structure from the Second World War.',
    city: 'Mechernich-Kommern',
    country: 'Germany',
    project_role: 'intern',
    project_type: 'Rescue excavation',
    organisation: 'LVR Rheinland',
  },
  {
    id: 6,
    project_name: 'Inden',
    tasks: 'trench supervision ',
    skills_learned: 'excavator training, trench supervision',
    start_date: '06.03.2012',
    end_date: '31.05.2012',
    longitude: 6.372,
    latitude: 50.835,
    description: '',
    city: 'Langerwehe',
    country: 'Germany',
    project_role: '',
    project_type: '',
    organisation: '',
  },
  {
    id: 7,
    project_name: 'Apollonia',
    tasks: 'surveying, trench supervision, documentation',
    skills_learned: 'single context recording system, Harris Matrix',
    start_date: '01.06.2012',
    end_date: '15.07.2012',
    longitude: 19.471823,
    latitude: 40.723359,
    description: '',
    city: 'Fier',
    country: 'Albania',
    project_role: 'intern',
    project_type: 'Research excavation',
    organisation: 'DAI Rome, archaeofact',
  },

  {
    id: 8,
    project_name: 'Grotte de la Verpillière I and II',
    tasks: 'surveying',
    skills_learned:
      'teachning survey methods, paleolithic excavation techniques',
    start_date: '29.07.2012',
    end_date: '30.09.2012',
    longitude: 4.752547,
    latitude: 46.811459,
    description:
      'In 2012 and 2013, I participated in an excavation project at two paleolithic caves in France, near the village of Germolles. The caves, known as Grotte de la Verpillière I and II, have been the subject of excavations since 2006, under the supervision of Prof. Harald Floss of the University of Tübingen in Germany. During my time on the project, I was responsible for surveying the site, as well as participating in the excavations using paleolithic excavation methods. This involved carefully digging through layers of sediment and soil to uncover artifacts and other remains from the paleolithic period. The excavation project at Grotte de la Verpillière I and II is ongoing, and continues to provide valuable insights into the lives of the people who lived in this region during the paleolithic era.',
    city: 'Germolles',
    country: 'France',
    project_role: '',
    project_type: 'Research excavation',
    organisation: 'University of Tübingen',
  },
];
