const projects = [
    {
        id: 1,
        project_name: "Weilerswist-Vernich",
        tasks: "earthworks",
        skills_learned: "",
        start_date: "01.10.2011",
        end_date: "09.11.2011",
        longitude: 6.83333,
        latitude: 50.76667,
        description: "Rescue excavation of an Iron Age trading post",
        city: "Weilerswist",
        country: "Germany",
        project_role: "intern",
        project_type: "Rescue excavation",
        organisation: "LVR Rheinland"
        },
        {
        id: 2,
        project_name: "Zülpich-Nemmenich",
        tasks: "technical drawings, descriptions, earthworks",
        skills_learned: "technical drawings, descriptions based on the Rheiniches Stellenkartensystem",
        start_date: "10.11.2011",
        end_date: "10.01.2012",
        longitude: 6.681311,
        latitude: 50.688141,
        description: "Rescue excavation of a Roman and Neolithic settlement.",
        city: "Zülpich",
        country: "Germany",
        project_role: "intern",
        project_type: "Rescue excavation",
        organisation: "LVR Rheinland",
        },
]